apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arkmq-org-broker-operator-role
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
